import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SmoothScroll from "@/components/SmoothScroll";
import AosProvider from '@/components/AosProvider';
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer"
import ChatBotWidget from "@/components/ChatBotWidget";
import "./globals.css";
// import { Poppins } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'],
//   variable: '--font-poppins', // Defines the CSS variable name
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CTS-Chiller Maintenance Company | HVAC Expert in UAE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${geistSans.variable} ${geistMono.variable} h-full antialiased overflow-x-hidden`}>
      <body className="bg-white text-slate-900 dark:bg-gray-950 dark:text-slate-100 transition-colors duration-300">
        <NavBar />
        <main className="flex-1 w-full"> <SmoothScroll> <AosProvider> {children} <ChatBotWidget/> </AosProvider> </SmoothScroll> </main>
        {/* Global Footer */}
        <Footer />
      </body>
    </html>
  );
}
